[package]
name = "hello_vst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
vst = "0.3.0"
wav = "1.0.0"
midi-types = "0.1.5"
cpal = "0.14.2"
crossbeam = "0.8.2"